diyan-lang/config/routes.rb
Rails.application.routes.draw do
  root 'static#index'

  devise_for :users

  resources :reports, except: [:show, :edit, :update] do
    get 'summary', on: :collection, as: :summary
    patch 'resolve', on: :member, as: :resolve
  end
end

diyan-lang/app/models/report.rb
# == Schema Information
#
# Table name: reports
#
#  id           :integer          not null, primary key
#  user_id      :integer
#  city_id      :integer
#  plate_number :string
#  description  :text
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  resolved     :boolean          default(FALSE)
#  first_name   :string
#  last_name    :string
#

class Report < ActiveRecord::Base
  belongs_to :user

  has_many :image_files, :dependent => :destroy

  self.per_page = 5

  def self.random_plate_number
    "#{('a'..'z').to_a.shuffle[0..2].join.upcase}-#{('0'..'9').to_a.shuffle[0..2].join}"
  end

  scope :search, ->(params) { 
    s = params[:search]
    result = all
    result = result.where('city_id = ?', s[:city]) unless s[:city].blank?
    result = result.where('plate_number LIKE ?', "%#{s[:plate_number]}%") unless s[:plate_number].blank?
    # result = result.where('EXTRACT(year FROMcreated_at) >= ?', s["start_date(1i)"].to_i) unless s["start_date(1i)"].blank?
    # result = result.where('end_date <= ?', s[:end_date]) unless s[:end_date].blank?
    result = result.where('resolved = ?', false) unless s[:show_resolved]
  }
end

diyan-lang/app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  load_and_authorize_resource
  before_action :set_report, only: [:show, :destroy, :resolve]

  # GET /reports
  def index
    if current_user.official?
      if params[:search]
        @reports = Report.page(params[:page]).search(params).order(created_at: :desc)
      else
        @reports = Report.page(params[:page]).where('resolved = ?', false).order(created_at: :desc)
      end
    else
      @reports = current_user.reports.page(params[:page]).order(created_at: :desc)
    end
  end

  # GET /reports/summary
  def summary
    @reports = Report.all
    @chart = GoogleVisualr::Interactive::BarChart.new(City::make_chart(@reports), City::chart_options)
  end

  # GET /reports/1
  def show
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  # POST /reports
  def create
    @report = Report.new(report_params)
    if @report.save
      if params[:image_files]
        params[:image_files].each do |image|
          @report.image_files.create(content: image)
        end
      end
      redirect_to root_path, notice: 'Report was successfully submitted.'
    else
      render :new
    end
  end

  # DELETE /reports/1
  def destroy
    @report.destroy
    redirect_to reports_path, notice: 'Report was successfully rejected.'
  end
  
  # PATCH /reports/resolve
  def resolve
    if @report.update(resolved: true)
      redirect_to @report, notice: 'Report was successfully resolved.'
    else
      redirect_to @report, alert: 'Report could not be resolved.'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:report).permit(:user_id, :city_id, :plate_number, :description)
    end
end

diyan-lang/app/helpers/reports_helper.rb
module ReportsHelper
end

diyan-lang/app/views/reports/_form.html.erb
<%= form_for(@report, html: { :class => "ui form", multipart: true }) do |f| %>
  <% if @report.errors.any? %>
    <div class="ui error message">
      <div class="header"><%= pluralize(@report.errors.count, "error") %> prohibited this report from being submitted:</div>

      <ul>
      <% @report.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if current_user.nil? %>
    <div class="two fields">
      <div class="field">
        <%= f.label :first_name, "First Name" %>
        <%= f.text_field :first_name %>
      </div>
      <div class="field">
        <%= f.label :last_name, "Last Name" %>
        <%= f.text_field :last_name %>
      </div>
    </div>
  <% else %>
    <div class="field">
      <%= hidden_field_tag("report[user_id]", current_user.id) %>
    </div>
  <% end %>

  <div class="two fields">
    <div class="field">
      <% cities = (0...City::NCR.size).to_a.map { |c| [City::NCR[c].split.map(&:capitalize).join(' '), c] } %>
      <%= f.label :city_id, "City" %>
      <%= f.select :city_id, options_for_select(cities) %>
    </div>

    <div class="field">
      <%= f.label :plate_number, "Plate Number" %>
      <%= f.text_field :plate_number, placeholder: "ABC-123" %>
    </div>
  </div>

  <div class="field">
    <%= f.label :images %>
    <%= file_field_tag "image_files[]", type: :file, multiple: true %>
    <p>Please include a timestamped photo(s) to ensure the credibility of your report. Fraudulent reports will be rejected.</p>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description, placeholder: "Enter an optional description of the offense." %>
  </div>

  <div class="actions">
    <%= f.submit "File Report", :class => "ui button" %>
    <%= render 'button', text: 'Cancel', url: root_path %>
  </div>
<% end %>

diyan-lang/app/views/reports/_old_index.html.erb
<%= form_tag reports_path, method: 'get' do %>
      <%= hidden_field_tag :direction, params[:direction] %>
      <%= hidden_field_tag :sort, params[:sort] %>
      <p style="display:none;">
        <%= text_field_tag :search, params[:search], placeholder: 'Enter a city' %>
        <%= submit_tag 'Search', name: nil %>
      </p>
    <% end %>

    <table class="ui table">
      <thead>
        <tr>
          <th>Date</th>
          <th>City</th>
          <th>Plate No.</th>
          <th>Description</th>
          <th>Resolved</th>
          <th>Open Report</th>
        </tr>
      </thead>
      <tbody>
        <% @reports.each do |report| %>
          <tr>
            <td><%= report.created_at %></td>
            <td><%= City::NCR[report.city_id] %></td>
            <td><%= report.plate_number %></td>
            <td><%= report.description.truncate 32 %></td>
            <td><% if report.resolved? %>Yes<% else %>No<% end %></td>
            <td><%= link_to "Open", report %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </section>

diyan-lang/app/views/reports/_search_form.html.erb
<%= form_tag reports_path, method: :get, :class => "ui form" do %>
  <div class="field">
    <%= label_tag "search[plate_number]", "Plate Number" %>
    <%= text_field_tag "search[plate_number]", nil, placeholder: "Enter a complete or partial plate number"  %>
  </div>

  <div class="field">
    <% cities = (0...City::NCR.size).to_a.map { |c| [City::NCR[c].split.map(&:capitalize).join(' '), c] } %>
    <%= label_tag "search[city]", "City" %>
    <%= select_tag "search[city]", options_for_select(cities), prompt: "Select a city" %>
  </div>

  <div class="two fields">
    <div class="eight wide field">
      <%= label_tag :start_date, "Starting From" %>
      <div class="three fields">
        <%= date_select "search", "start_date", prompt: { day: 'Select day', month: 'Select month', year: 'Select year' } %>
      </div>
    </div>

    <div class="eight wide field">
      <%= label_tag :end_date, "Up To" %>
      <div class="three fields">
        <%= date_select "search", "end_date", prompt: { day: 'Select day', month: 'Select month', year: 'Select year' } %>
      </div>
    </div>
  </div>

  <div class="field">
    <%= check_box_tag "search[show_resolved]", "1" %>
    <%= label_tag :show_resolved, "Show resolved", style: "display:inline;", title: "Display already resolved cases." %>
  </div>

  <div class="actions">
    <%= submit_tag "Reload", :class => "ui button" %>
    <%= render 'button', text: 'View Summary', url: summary_reports_path %>
    <%= render 'button', text: 'Cancel', url: root_path %>
  </div>
<% end %>

diyan-lang/app/views/reports/index.html.erb
<%= render 'navbar' %>
<section class="ui container">
  <section class="ui detailed-report segments">
    <section class="ui heading segment"><h1>Traffic Violation Reports</h1></section>
    <% if current_user.official? %>
      <section class="ui controls segment">
        <h2>Options</h2>
        <%= render 'search_form' %>
      </section>
    <% end %>
    <% @reports.each do |report| %>
      <section class="ui content segment">
        <h2><%= report.plate_number %>
          (<%= City::NCR[report.city_id] %>,
          <%= report.created_at.strftime "%B %d, %Y - %H:%m:%S" %>)
          <% if report.resolved? %>[RESOLVED]<% end %>
        </h2>
        <% if current_user.official? %>
          <p><strong>Complainant:</strong>
            <% if report.user_id %>
              <%= "#{report.user.first_name} #{report.user.last_name}" %>
            <% else %>
              <%= "#{report.first_name} #{report.last_name}" %>
            <% end %>
          </p>
        <% end %>
        <% if report.resolved %>
          <p><strong>Resolved:</strong> Yes</p>
        <% else %>
          <p><strong>Resolved:</strong> No</p>
        <% end %>
        <p><strong>Description:</strong> <%= report.description %></p>
        <% report.image_files.each do |img| %>
         <%= image_tag img.content.url(:medium) %><br />
        <% end %>
        <br />
        <% if current_user.official? && !report.resolved? %>
          <div class="ui button"><%= link_to 'Resolve', resolve_report_path(report), method: :patch, data: { confirm: 'Are you sure?' } %></div>
          <div class="ui button"><%= link_to 'Reject', report, method: :delete, data: { confirm: 'Are you sure?' } %></div>
        <% end %>
      </section>
    <% end %>
    <section class="ui segment">
      <%= will_paginate @reports, :class => "ui menu" %>    
    </section>
  </sectio  n>
</section>

diyan-lang/app/views/reports/new.html.erb
<%= render 'navbar' %>
<section class="ui container">
  <section class="ui file-report segments">
    <section class="ui heading segment">
      <h1>File a Report</h1>
    </section>
    <section class="ui -form segment">
      <%= render 'form' %>
    </section>
  </section>
</section>

diyan-lang/app/views/reports/show.html.erb
<h1>Report</h1>
<p><strong>Date:</strong> <%= @report.created_at %></p>
<p><strong>Resolved:</strong> <% if @report.resolved? %>Yes<% else %>No<% end %></p>
<p><strong>Complainant:</strong> <%= @report.user.email %></p>
<p><strong>Offender Plate Number:</strong> <%= @report.plate_number %></p>
<p><strong>Description:</strong> <%= @report.description %></p>
<% @report.image_files.each do |img| %>
 <%= image_tag img.content.url(:medium) %>
<% end %>
<% unless @report.resolved? %>
  <%= link_to 'Resolve', resolve_report_path(@report), method: :patch, data: { confirm: 'Are you sure?' } %>
<% end%>

diyan-lang/app/views/reports/summary.html.erb
<%= render 'navbar' %>
<section class="ui container">
  <section class="ui report-summary segments">
    <section class="ui heading segment">
      <h1>Summary of Reports</h1>
    </section>
    <section class="ui content segment">
      <div class="ui stackable grid">
        <div class="five wide column">      
          <table class="ui celled table">
            <thead>
              <tr>
                <th>City</th>
                <th>Incidents</th>
              </tr>
            </thead>
            <tbody>
              <% City::NCR.count.times do |id| %>
                <tr>
                  <td><%= City::NCR[id] %></td>
                  <td><%= @reports.where('city_id = ?', id).count %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
        <div class="eleven wide column">
          <div style="margin:auto;" id="chart"></div>
          <%= render_chart(@chart, 'chart') %>
          <%= render 'button', text: 'View Detailed Reports', url: reports_path %>
          <%= render 'button', text: 'Back', url: root_path %>
        </div>
      </div>
    </section>
  </section>
</section>